name: Android CI

on:
  push:
    branches: [ main, test_secret ]
  pull_request:
    branches:
      - main
      - demo_*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Access FIREBASE_DB_URL
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
        run: echo db_url=\"$FIREBASE_DB_URL\" > ./local.properties

      - name: Access GOOGLE_SERVICES
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES > ./app/google-services.json

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
